#!/usr/bin/env bash

# Check if script is already running
check="$(pgrep -fl wf-recorder)"
if [ -n "$check" ]; then
  notify-send -t 1000 "Screen Recording has been stopped"
  killall --user $USER  --ignore-case  --signal INT wf-recorder
else
  notify-send -t 1000 "Screen Recording has been started"

    # Get the name of the currently focused monitor
  monitor_name=$(hyprctl monitors -j | jq -r '.[] | select(.focused) | .name')
  
  # Record the selected monitor
  wf-recorder -o "${monitor_name}" -f "$HOME/Videos/$(date +%d_%m_%H:%M)".mp4 -c h264_vaapi -d /dev/dri/renderD128
fi
