#!/bin/zsh

# Find the first available workspace number
workspaces=$(aerospace list-workspaces --all)
candidate=0
while [[ $workspaces == *"$candidate"* ]]; do
  candidate=$((candidate+1))
done

aerospace move-node-to-workspace $candidate && aerospace workspace $candidate


for monitor in $(aerospace list-monitors --format %{monitor-id}); do
    should_destroy=false
    for sid in $(aerospace list-workspaces --monitor $monitor); do
        if [ "$sid" = "$candidate" ]; then
            should_destroy=true
            continue
        fi

        if $should_destroy; then
            sketchybar --remove space.$sid
        fi
    done
done

for monitor in $(aerospace list-monitors --format %{monitor-id}); do
    for sid in $(aerospace list-workspaces --monitor $monitor); do
        sketchybar --add item space.$sid left \
            --subscribe space.$sid aerospace_workspace_change \
            --set space.$sid \
            display=$monitor \
            background.color=0xff313244 \
            label.padding_left=0 \
            label.padding_right=10 \
            label="$sid" \
            click_script="aerospace workspace $sid" \
            script="~/.config/sketchybar/plugins/aerospace.sh $sid"
    done
done


sketchybar --set space.$(aerospace list-workspaces --focused) background.drawing=on label.color=0xff1E1E2E background.color=0xffB4BEFE
