#!/bin/zsh

aerospace move-workspace-to-monitor --wrap-around $1

sketchybar --trigger aerospace_focus_change

for monitor in $(aerospace list-monitors --format %{monitor-id}); do
    reorder_array=()
    for sid in $(aerospace list-workspaces --monitor "$monitor"); do
        reorder_array+=("space.$sid")
    done
    sketchybar --reorder "${reorder_array[@]}"
done
