#!/bin/zsh

# Find the first available workspace number
workspaces=$(aerospace list-workspaces --all)
candidate=0
while [[ $workspaces == *"$candidate"* ]]; do
  candidate=$((candidate+1))
done

aerospace move-node-to-workspace $candidate && aerospace workspace $candidate


for monitor in $(aerospace list-monitors --format %{monitor-id}); do
    should_destroy=false
    for sid in $(aerospace list-workspaces --monitor $monitor); do
        if [ "$sid" = "$candidate" ]; then
            should_destroy=true
            continue
        fi

        if $should_destroy; then
            sketchybar --remove space.$sid
        fi
    done
done

source ~/.config/sketchybar/colors.sh

for monitor in $(aerospace list-monitors --format %{monitor-id}); do
    for workspace in $(aerospace list-workspaces --monitor $monitor); do
        sketchybar --add item space.$workspace left \
            --subscribe space.$workspace aerospace_workspace_change space_windows_change display_change \
            --set space.$workspace \
            display=$monitor \
            background.color=$SURFACE_COLOR \
            icon="$workspace" \
            icon.color=$SUBTEXT_COLOR \
            label.font="sketchybar-app-font:Regular:15.0" \
            label.y_offset=-1 \
            click_script="aerospace workspace $workspace" \
            script="~/.config/sketchybar/plugins/aerospace.sh $workspace"
    done
done

sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)
